### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode byte 0xd7 in position 1580: illegal multibyte sequence

### ISSUE THREAD

**Issue by xoyojank** [Makiah/BotW-SBFRES-to-FBX#13]
***Phase 4: Model Exports***
Traceback (most recent call last):
  File "runme.py", line 66, in <module>
    LoadAndExportExtractedModels.loadAndExportModels()
  File "E:\BotW-SBFRES-to-FBX\fbxextraction\LoadAndExportExtractedModels.py", line 48, in loadAndExportModels
    data = file.readlines()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xd7 in position 1580: illegal multibyte sequence

**Comment by Makiah** [comment]
Presumably fixed by 39f1485
